### ISSUE TITLE
bad 0.0.2 version on pypi

### ISSUE THREAD

**Issue by chassing** [ShaneDrury/dockerintegration#6]
I tried to update to 0.0.2 but it looks like there is still 0.0.1 tagged as 0.0.2 on pypi :( very strange. First I did a `pip install -U docker-integration`, pip reports 0.0.2 is installed but docker.py has still the 0.0.1 content. I've downloaded 0.0.2 via https://pypi.python.org/pypi/docker-integration/0.0.2 and the tar.gz has indeed the 0.0.1 content but taggged as 0.0.2

**Comment by ShaneDrury** [comment]
Huh, that's odd. I can confirm that the tar.gz has the old content... I'll look into this and may have to bump to 0.0.3.

**Comment by ShaneDrury** [comment]
OK, should be fixed now. I've bumped the version and uploaded to PyPI. Pip installed and checked that the code is the updated stuff.

**Comment by chassing** [comment]
0.0.3 is working now. thx
